import { useRef } from "react";
import { C } from "../../data/seed";
import { Eyebrow, SectionTitle, GlowDivider, Card, Btn } from "../shared";
import type { Worker, Job } from "../../types";

const getLevel = (jobsDone: number) => {
  if (jobsDone >= 11) return "Expert";
  if (jobsDone >= 5) return "Intermediate";
  return "Beginner";
};

export function AdminWorkerReport({ workers, jobs }: { workers: Worker[]; jobs: Job[] }) {
  const printRef = useRef<HTMLDivElement>(null);

  const getWorkerStats = (w: Worker) => {
    const approved = jobs.filter(j => j.status === "Approved" && j.submissions.some(s => s.workerId === w.id));
    const submitted = jobs.filter(j => j.submissions.some(s => s.workerId === w.id));
    const lateCount = jobs.reduce((n, j) => n + j.submissions.filter(s => s.workerId === w.id && s.late).length, 0);
    const totalEarned = approved.reduce((s, j) => {
      const sub = j.submissions.find(sb => sb.workerId === w.id);
      return s + (sub?.pay || 0);
    }, 0);
    return { approved: approved.length, submitted: submitted.length, lateCount, totalEarned };
  };

  const handlePrint = () => {
    const content = printRef.current;
    if (!content) return;
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(`
      <html>
      <head>
        <title>Turris Forge — Worker Performance Report</title>
        <style>
          * { box-sizing: border-box; margin: 0; padding: 0; }
          body { font-family: 'Georgia', serif; background: #fff; color: #111; padding: 40px; }
          h1 { font-size: 28px; margin-bottom: 4px; }
          .sub { font-size: 12px; color: #666; margin-bottom: 32px; }
          table { width: 100%; border-collapse: collapse; font-size: 13px; }
          th { background: #111; color: #fff; padding: 10px 12px; text-align: left; font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; }
          td { padding: 10px 12px; border-bottom: 1px solid #eee; vertical-align: top; }
          tr:nth-child(even) td { background: #f9f9f9; }
          .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 10px; font-weight: bold; }
          .expert { background: #FFF3CD; color: #856404; }
          .intermediate { background: #D1ECF1; color: #0C5460; }
          .beginner { background: #D4EDDA; color: #155724; }
          .banned { color: #C0392B; font-weight: bold; }
          footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
        </style>
      </head>
      <body>
        ${content.innerHTML}
        <footer>Generated by Turris Forge Admin Portal · ${new Date().toLocaleString("en-NG")}</footer>
      </body>
      </html>
    `);
    win.document.close();
    setTimeout(() => { win.print(); }, 500);
  };

  return (
    <div>
      <Eyebrow color={C.pink}>Admin</Eyebrow>
      <SectionTitle>Worker Performance Report</SectionTitle>
      <GlowDivider colors={[C.pink, C.violet2]} />

      <div style={{ marginBottom: 20, display: "flex", justifyContent: "flex-end" }}>
        <Btn onClick={handlePrint} style={{ padding: "10px 24px", fontSize: 12, background: `${C.pink}22`, border: `1px solid ${C.pink}55`, color: C.pink }}>
          🖨️ Print / Save as PDF
        </Btn>
      </div>

      {/* Preview */}
      <Card>
        <div ref={printRef}>
          <h1 style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 28, color: C.ash, marginBottom: 4 }}>Turris Forge</h1>
          <div style={{ fontSize: 11, color: C.gray, fontFamily: "'Barlow Condensed',sans-serif", letterSpacing: "0.2em", textTransform: "uppercase", marginBottom: 24 }}>
            Worker Performance Report · {new Date().toLocaleDateString("en-NG", { day: "numeric", month: "long", year: "numeric" })}
          </div>

          <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 13 }}>
              <thead>
                <tr>
                  {["Worker", "Level", "Skills", "Submitted", "Approved", "Late", "Earned", "Rating", "Status"].map(h => (
                    <th key={h} style={{ padding: "10px 12px", background: "#111", color: "#fff", textAlign: "left", fontSize: 10, letterSpacing: "0.1em", textTransform: "uppercase" }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {[...workers].sort((a, b) => b.balance - a.balance).map((w, i) => {
                  const s = getWorkerStats(w);
                  const lvl = getLevel(s.approved);
                  return (
                    <tr key={w.id} style={{ background: i % 2 === 0 ? C.sur : C.bg }}>
                      <td style={{ padding: "10px 12px", color: C.ash }}>
                        <div style={{ fontWeight: 600 }}>{w.name}</div>
                        <div style={{ fontSize: 10, color: C.gray }}>{w.email}</div>
                      </td>
                      <td style={{ padding: "10px 12px" }}>
                        <span style={{ fontSize: 10, padding: "2px 8px", borderRadius: 10, background: lvl === "Expert" ? "#E8912A22" : lvl === "Intermediate" ? "#00E5FF22" : "#A8FF3E22", color: lvl === "Expert" ? "#E8912A" : lvl === "Intermediate" ? "#00E5FF" : "#A8FF3E", fontFamily: "'Barlow Condensed',sans-serif" }}>
                          {lvl}
                        </span>
                      </td>
                      <td style={{ padding: "10px 12px", fontSize: 11, color: C.gray }}>{w.skills.slice(0, 2).join(", ") || "—"}</td>
                      <td style={{ padding: "10px 12px", color: C.cyan, textAlign: "center" }}>{s.submitted}</td>
                      <td style={{ padding: "10px 12px", color: C.lime, textAlign: "center" }}>{s.approved}</td>
                      <td style={{ padding: "10px 12px", color: s.lateCount > 0 ? "#E74C3C" : C.gray, textAlign: "center" }}>{s.lateCount}</td>
                      <td style={{ padding: "10px 12px", color: C.gold }}>₦{s.totalEarned.toLocaleString()}</td>
                      <td style={{ padding: "10px 12px", color: C.gold }}>{w.rating > 0 ? `${w.rating.toFixed(1)} ★` : "—"}</td>
                      <td style={{ padding: "10px 12px" }}>
                        {w.banned
                          ? <span style={{ color: "#C0392B", fontSize: 11 }}>🚫 Banned</span>
                          : <span style={{ color: C.lime, fontSize: 11 }}>✅ Active</span>}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div style={{ marginTop: 24, display: "flex", gap: 24, flexWrap: "wrap" }}>
            {[
              ["Total Workers", workers.length, C.cyan],
              ["Active Workers", workers.filter(w => !w.banned).length, C.lime],
              ["Banned Workers", workers.filter(w => w.banned).length, "#C0392B"],
              ["Total Paid Out", `₦${workers.reduce((s, w) => s + w.balance, 0).toLocaleString()}`, C.gold],
            ].map(([l, v, c]) => (
              <div key={String(l)} style={{ textAlign: "center", padding: "12px 20px", background: C.sur, borderRadius: 8, border: `1px solid #ffffff08` }}>
                <div style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 24, color: String(c) }}>{String(v)}</div>
                <div style={{ fontSize: 10, color: C.gray, fontFamily: "'Barlow Condensed',sans-serif", letterSpacing: "0.15em", textTransform: "uppercase", marginTop: 4 }}>{String(l)}</div>
              </div>
            ))}
          </div>
        </div>
      </Card>
    </div>
  );
}
